//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hairdreams_Long {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hairdreams_Long() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Hairdreams.Long", typeof(Hairdreams_Long).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieufactoren, stress en chemische behandelingen hebben een invloed op de kwaliteit van uw haren. Ermee rekening houdend dat haar ook regelmatig moet geknipt worden om gezond te houden kan het lang duren (haar groeit ca. 1 cm per maand) vooraleer de droom van lang en gezond natuurlijk haar wordt verwezenlijkt. Vergeet daarnaast ook niet dat natuurlijke aanleg en eetgewoonten een belangrijke rol spelen..
        /// </summary>
        internal static string ArticleLongHairdreamsParagraph1 {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veel vrouwen geloven niet dat “extensies” de oplossing bieden voor hun problemen, want het lijkt onnatuurlijk of beschadigd het haar. Wat meer is, ze gaan ervan uit dat iedereen kan zien dat het haar kunstmatig is....
        /// </summary>
        internal static string ArticleLongHairdreamsParagraph2 {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niets is minder waar….
        /// </summary>
        internal static string ArticleLongHairdreamsParagraph3 {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams biedt de oplossing.
        /// </summary>
        internal static string ArticleLongHairdreamsSolution {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams haarcreaties bieden nu sneller en eenvoudiger dan ooit een antwoord op al uw dromen. De strengen zijn vrijwel niet te onderscheiden van natuurlijk haar en kunnen in slechts een paar uur worden aangebracht. U kunt nu naar wens lengte en volume aan uw haar toevoegen en vrijwel elke droomkapsel bekomen..
        /// </summary>
        internal static string ArticleLongHairdreamsSolutionParagraph {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsSolutionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang haar is altijd al de belichaming van vrouwelijke schoonheid geweest. Er is nog niets veranderd, maar tijdens het nastreven van deze droom wordt men vaak met diverse obstakels geconfronteerd..
        /// </summary>
        internal static string ArticleLongHairdreamsSubTitle {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams laat u dromen over lang haar.
        /// </summary>
        internal static string ArticleLongHairdreamsTitle {
            get {
                return ResourceManager.GetString("ArticleLongHairdreamsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Hairdreams.
        /// </summary>
        internal static string LongHairdreams {
            get {
                return ResourceManager.GetString("LongHairdreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Extenties&quot; behoren tot het verleden. Nu is het tijd om kapsels te &quot;creëren&quot;!
        ///Haarverlenging op het hoogste niveau met 100% echt menselijk haar..
        /// </summary>
        internal static string LongHairdreamsText {
            get {
                return ResourceManager.GetString("LongHairdreamsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams haarverlengingen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
