//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hairdreams_Volume {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hairdreams_Volume() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Hairdreams.Volume", typeof(Hairdreams_Volume).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlines.
        /// </summary>
        internal static string Highlines {
            get {
                return ResourceManager.GetString("Highlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Hairdreams Highlines geeft volume aan dun en schaars haar in het bovenste deel van het hoofd door op het eigen haar van de klant een speciaal onzichtbaar net te plaatsen, waarin hoogwaardige echte haren worden ingevlochten..
        /// </summary>
        internal static string HighlinesIntroText {
            get {
                return ResourceManager.GetString("HighlinesIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indien gewenst kan een andere kleur van extra strengen gekozen worden om een aantrekkelijk kleureffect te creëren..
        /// </summary>
        internal static string HighlinesIntroText2 {
            get {
                return ResourceManager.GetString("HighlinesIntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams Volume+ HighLines.
        /// </summary>
        internal static string HighlinesTitle {
            get {
                return ResourceManager.GetString("HighlinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met het Volume+ gamma van Hairdreams kunt u onmiddellijk volume geven aan dun en schaars haar. Het gamma biedt verschillende mogelijkheden voor volumecreatie en kan voor elke individuele situatie een oplossing bieden, van normaal en dun haar tot schaars haar..
        /// </summary>
        internal static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dankzij Hairdreams kunnen de mensen die worstelen met het probleem van plaatselijke kaalheid van dik haar genieten, zelfs in het geval van gevorderde haaruitval. Eigen haar wordt aangevuld en verdikt met hoogwaardig echt haar dat aan handmatige selectie werd onderworpen. Dit haar wordt afgestemd aan het eigen haar in termen van kleur, lengte en structuur om een om zo natuurlijk mogelijk resultaat te creëren. Het verbindingsproces verloopt op een wijze die zacht en onschadelijk is voor het haar. De klant voe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntroText2 {
            get {
                return ResourceManager.GetString("IntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microlines.
        /// </summary>
        internal static string Microlines {
            get {
                return ResourceManager.GetString("Microlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De MicroLines methode is ideaal geschikt om op natuurlijke wijze haar op het hoofd te verdikken, zelfs bij gevorderde haaruitval..
        /// </summary>
        internal static string MicrolinesIntroText {
            get {
                return ResourceManager.GetString("MicrolinesIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicroLines is een net gemaakt met vrijwel onzichtbare, speciale, zeer dunne garen, waarop hoogwaardig echt haar bevestigd zijn. Ze worden aan het haar van de klant toegepast in termen van kleur, lengte en structuur, dus ze worden op een onzichtbare manier gemengd met het haar van de klant. Het resultaat is een volledig natuurlijk kapsel dat niet van natuurlijk haar kan worden onderscheiden..
        /// </summary>
        internal static string MicrolinesIntroText2 {
            get {
                return ResourceManager.GetString("MicrolinesIntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams Volume+ MicroLines.
        /// </summary>
        internal static string MicrolinesTitle {
            get {
                return ResourceManager.GetString("MicrolinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams haarverdikkingen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams Volume+ Haarverdikking.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tophair.
        /// </summary>
        internal static string Tophair {
            get {
                return ResourceManager.GetString("Tophair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De innovatieve TopHair methode van Hairdreams is snel, comfortabel en flexibel, en ideaal om snel en probleemlos dun en schaars haar op de bovenste gedeelte van het hoofd op te vullen. Door het speciale ontwerp is het perfect om lang haar te verkrijgen alsook kapsels met een scheiding..
        /// </summary>
        internal static string TophairIntroText {
            get {
                return ResourceManager.GetString("TophairIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt gemaakt uit een modern, ademend net met ingevlochten strengen van Hairdreams, dat wordt bevestigd aan het haar van de klant in het bovenste gedeelte van het hoofd. Andere strengen worden onzichbaar verbonden met eigen haar, waardoor de zachte en natuurlijke kapsels ontstaan met langere haren, evenals scheidingen en een pony..
        /// </summary>
        internal static string TophairIntroText2 {
            get {
                return ResourceManager.GetString("TophairIntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams Volume+ Top Hair.
        /// </summary>
        internal static string TophairTitle {
            get {
                return ResourceManager.GetString("TophairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume+ Hairdreams.
        /// </summary>
        internal static string VolumeHairdreams {
            get {
                return ResourceManager.GetString("VolumeHairdreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droomvolume verkregen door de HAIRDREAMS methode van haarverlenging en -verdikking.
        /// </summary>
        internal static string VolumeHairdreamsText {
            get {
                return ResourceManager.GetString("VolumeHairdreamsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume+ HighLines – hoe het werkt:.
        /// </summary>
        internal static string VolumeHighlinesHairdreamsHow {
            get {
                return ResourceManager.GetString("VolumeHighlinesHairdreamsHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Highlines is vast bevestigd aan de bovenkant van het hoofd met een speciale lijm. De haren van de klant door het net geweven en worden mooi gemengd met de strengen van Hairdreams. Deze methode maakt het mogelijk om nagenoeg elk kapsel te creëren dat dik haar in het bovenste gedeelte van het hoofd vereist. Een draagperiode van HighLines is ca. 6-8 maanden..
        /// </summary>
        internal static string VolumeHighlinesHairdreamsHowText {
            get {
                return ResourceManager.GetString("VolumeHighlinesHairdreamsHowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume+ MicroLines – hoe het werkt:.
        /// </summary>
        internal static string VolumeMicrolinesHairdreamsHow {
            get {
                return ResourceManager.GetString("VolumeMicrolinesHairdreamsHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De MicroLines methode verdikt het haar van de klant met een vrijwel onzichtbaar fijn haarnet. Speciale garen gemaakt van kristallijn polymeer worden voorzichtig maar stevig in haar bevestigd, waarop de hoogwaardige echte haren verbonden worden, die in kleur en haarlengte aan klant haar haar worden aangepast. Zo krijgt het haar van de klant een meer natuurlijk volume op het hoofd. Der daagperiode van MicroLines is ca. 6-8 maanden..
        /// </summary>
        internal static string VolumeMicrolinesHairdreamsHowText {
            get {
                return ResourceManager.GetString("VolumeMicrolinesHairdreamsHowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume+ TopHair – hoe het werkt:.
        /// </summary>
        internal static string VolumeTophairHairdreamsHow {
            get {
                return ResourceManager.GetString("VolumeTophairHairdreamsHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Hairdreams Tophair worden aan het haar van de cliënte in het bovenste gedeelte van het hoofd bevestigd met de klemmen. Deze methode maakt het mogelijk om het haar op deze plaatsen te verdikken en te verlengen en het maken van kapsels met nauwkeurige scheidingen. De cliënte kan ze zelf eenvoudig verwijderen en opnieuw opzetten. Tophair kan ook permanent bevestigd worden met behulp van een speciale lijm. De hechting dient dan om de 4-6 weken opnieuw te worden uitgevoerd ten gevolge van de uitgroei van het  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VolumeTophairHairdreamsHowText {
            get {
                return ResourceManager.GetString("VolumeTophairHairdreamsHowText", resourceCulture);
            }
        }
    }
}
