//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hairdreams_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hairdreams_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Hairdreams.Index", typeof(Hairdreams_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu reserveren.
        /// </summary>
        internal static string HairdreamsBookingButton {
            get {
                return ResourceManager.GetString("HairdreamsBookingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geïnteresseerd? Maak nu een afspraak voor een GRATIS consultatiegesprek!.
        /// </summary>
        internal static string HairdreamsCallToAction {
            get {
                return ResourceManager.GetString("HairdreamsCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davina&apos;s Coiffure Shop is reeds jaren een trouwe partner van Hairdreams. Met Hairdreams kiezen we voor topkwaliteit op alle fronten. De haren en producten van Hairdreams zijn over de hele lijn van wereldniveau. Gecombineerd met een top-of-the-line trainingsprogramma zitten we op alle vlakken meer dan goed. Het is niet zonder reden dat Hairdreams &apos;s werelds nr. 1 is in haarverlengingen en haarcreatie..
        /// </summary>
        internal static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdreams haarverlengingen en meer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
