//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home_Appointment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_Appointment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Home.Appointment", typeof(Home_Appointment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonisch een afspraak maken.
        /// </summary>
        internal static string ByTelephone {
            get {
                return ResourceManager.GetString("ByTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijdens de openingsuren zijn wij steeds telefonisch bereikbaar.&lt;br/&gt;Telefonisch een afspraak maken is mogelijk op het nummer 059 730 185.&lt;br/&gt;Indien u niet kunt bellen kunt u steeds online een afspraak boeken..
        /// </summary>
        internal static string ByTelephoneText {
            get {
                return ResourceManager.GetString("ByTelephoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een afspraak.
        /// </summary>
        internal static string H3Title {
            get {
                return ResourceManager.GetString("H3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online een afspraak maken.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het is ook mogelijk om online een afspraak te maken.&lt;br/&gt;Klik op onderstaande knop om de boekingsapp te openen..
        /// </summary>
        internal static string OnlineText {
            get {
                return ResourceManager.GetString("OnlineText", resourceCulture);
            }
        }
    }
}
