//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home_Parking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_Parking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Home.Parking", typeof(Home_Parking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Parkeren in Oostende&lt;/h1&gt;
        ///&lt;div class=&quot;col-md-8 map&quot;&gt;
        ///    &lt;div class=&quot;mapouter&quot;&gt;
        ///        &lt;div class=&quot;responsive-map&quot;&gt;
        ///            &lt;iframe id=&quot;gmap_canvas&quot; src=&quot;https://maps.google.com/maps?q=davina&apos;s%20coiffure%20shop&amp;t=&amp;z=17&amp;ie=UTF8&amp;iwloc=&amp;output=embed&quot;&gt;&lt;/iframe&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div class=&quot;col-md-4&quot;&gt;
        ///    &lt;h3&gt;Davina&apos;s Coiffure Shop&lt;/h3&gt;
        ///    &lt;p&gt;
        ///        Wittenonnenstraat 34&lt;br /&gt;
        ///        8400 Oostende
        ///    &lt;/p&gt;
        ///    &lt;h4&gt;GPS-coördinaten:&lt;/h4&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeren in Oostende.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
