//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Service_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Service_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.Views.Service.Index", typeof(Service_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to van 10 tot 14 jaar.
        /// </summary>
        internal static string Age10to14 {
            get {
                return ResourceManager.GetString("Age10to14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baard knippen.
        /// </summary>
        internal static string BeardTrim {
            get {
                return ResourceManager.GetString("BeardTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoonheidsbad.
        /// </summary>
        internal static string Beautybath {
            get {
                return ResourceManager.GetString("Beautybath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond pro.
        /// </summary>
        internal static string Bondpro {
            get {
                return ResourceManager.GetString("Bondpro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruidskapsel.
        /// </summary>
        internal static string BrideHair {
            get {
                return ResourceManager.GetString("BrideHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushing lang.
        /// </summary>
        internal static string BrushingLong {
            get {
                return ResourceManager.GetString("BrushingLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushing halflang.
        /// </summary>
        internal static string BrushingMedium {
            get {
                return ResourceManager.GetString("BrushingMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushing of watergolf.
        /// </summary>
        internal static string BrushingOrRollerWrap {
            get {
                return ResourceManager.GetString("BrushingOrRollerWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushing kort.
        /// </summary>
        internal static string BrushingShort {
            get {
                return ResourceManager.GetString("BrushingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinderen.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmen.
        /// </summary>
        internal static string ClipperCut {
            get {
                return ResourceManager.GetString("ClipperCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleuren.
        /// </summary>
        internal static string Coloring {
            get {
                return ResourceManager.GetString("Coloring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krultang.
        /// </summary>
        internal static string CurlingIron {
            get {
                return ResourceManager.GetString("CurlingIron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knippen.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra kleur Elumen (10g).
        /// </summary>
        internal static string ExtraColorElumen {
            get {
                return ResourceManager.GetString("ExtraColorElumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra kleur Goldwell (30g).
        /// </summary>
        internal static string ExtraColorGoldwell {
            get {
                return ResourceManager.GetString("ExtraColorGoldwell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afwerking.
        /// </summary>
        internal static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mèches.
        /// </summary>
        internal static string FoilHighlights {
            get {
                return ResourceManager.GetString("FoilHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heren.
        /// </summary>
        internal static string Gentlemen {
            get {
                return ResourceManager.GetString("Gentlemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haarsnit.
        /// </summary>
        internal static string Haircut {
            get {
                return ResourceManager.GetString("Haircut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babysnit.
        /// </summary>
        internal static string HaircutBaby {
            get {
                return ResourceManager.GetString("HaircutBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jongenssnit.
        /// </summary>
        internal static string HaircutBoys {
            get {
                return ResourceManager.GetString("HaircutBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meisjessnit.
        /// </summary>
        internal static string HaircutGirls {
            get {
                return ResourceManager.GetString("HaircutGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meisjessnit + los drogen.
        /// </summary>
        internal static string HaircutGirls10to14 {
            get {
                return ResourceManager.GetString("HaircutGirls10to14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balayage.
        /// </summary>
        internal static string Highlights {
            get {
                return ResourceManager.GetString("Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensief verzorgingsmasker.
        /// </summary>
        internal static string IntensiveCareMask {
            get {
                return ResourceManager.GetString("IntensiveCareMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderstaand kunt u een prijslijst terugvinden van onze basisdiensten..
        /// </summary>
        internal static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet alle diensten konden opgenomen worden. Aarzel niet om ons te contacteren moest u bijkomende vragen hebben..
        /// </summary>
        internal static string IntroText2 {
            get {
                return ResourceManager.GetString("IntroText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dames.
        /// </summary>
        internal static string Ladies {
            get {
                return ResourceManager.GetString("Ladies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        internal static string Perm {
            get {
                return ResourceManager.GetString("Perm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorpigmentatie.
        /// </summary>
        internal static string PrePigmenting {
            get {
                return ResourceManager.GetString("PrePigmenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los drogen.
        /// </summary>
        internal static string QuickDry {
            get {
                return ResourceManager.GetString("QuickDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgroeikleuring.
        /// </summary>
        internal static string Regrowthcolor {
            get {
                return ResourceManager.GetString("Regrowthcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watergolf.
        /// </summary>
        internal static string RollerWrap {
            get {
                return ResourceManager.GetString("RollerWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losse mèches (per stuk).
        /// </summary>
        internal static string SeperateHighlights {
            get {
                return ResourceManager.GetString("SeperateHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vanaf.
        /// </summary>
        internal static string StartingFrom {
            get {
                return ResourceManager.GetString("StartingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontkrullen.
        /// </summary>
        internal static string Straighten {
            get {
                return ResourceManager.GetString("Straighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijltang/Steampod.
        /// </summary>
        internal static string StraighteningIronSteampod {
            get {
                return ResourceManager.GetString("StraighteningIronSteampod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ont)krullen.
        /// </summary>
        internal static string StraightenOrCurl {
            get {
                return ResourceManager.GetString("StraightenOrCurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementen.
        /// </summary>
        internal static string Supplements {
            get {
                return ResourceManager.GetString("Supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onze diensten.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te combineren met los drogen, brushing of watergolf.
        /// </summary>
        internal static string ToBeCombined {
            get {
                return ResourceManager.GetString("ToBeCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opkammen.
        /// </summary>
        internal static string TouchUp {
            get {
                return ResourceManager.GetString("TouchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsteekkapsel.
        /// </summary>
        internal static string Updo {
            get {
                return ResourceManager.GetString("Updo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsteekkapsel kinderen.
        /// </summary>
        internal static string UpdoChildren {
            get {
                return ResourceManager.GetString("UpdoChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsteekkapsel lang.
        /// </summary>
        internal static string UpdoLong {
            get {
                return ResourceManager.GetString("UpdoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsteekkapsel kort.
        /// </summary>
        internal static string UpdoShort {
            get {
                return ResourceManager.GetString("UpdoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wassen en verzorgen.
        /// </summary>
        internal static string WashAndCare {
            get {
                return ResourceManager.GetString("WashAndCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuten werk.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jonger dan 10 jaar.
        /// </summary>
        internal static string YoungerThan10 {
            get {
                return ResourceManager.GetString("YoungerThan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jonger dan 5 jaar.
        /// </summary>
        internal static string YoungerThan5 {
            get {
                return ResourceManager.GetString("YoungerThan5", resourceCulture);
            }
        }
    }
}
