//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSCoreMvc.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSCoreMvc.Localization.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar website.
        /// </summary>
        internal static string BackToWebsite {
            get {
                return ResourceManager.GetString("BackToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boek hier online.
        /// </summary>
        internal static string BookOnline {
            get {
                return ResourceManager.GetString("BookOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bel ons.
        /// </summary>
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.coiffureshop.com.
        /// </summary>
        internal static string CoiffureShopWebsite {
            get {
                return ResourceManager.GetString("CoiffureShopWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oostende.
        /// </summary>
        internal static string CompanyCity {
            get {
                return ResourceManager.GetString("CompanyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrijfsgegevens.
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVBA Davina&apos;s Coiffure en Schoonheidssalon.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8400.
        /// </summary>
        internal static string CompanyPostalCode {
            get {
                return ResourceManager.GetString("CompanyPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wittenonnenstraat.
        /// </summary>
        internal static string CompanyStreet {
            get {
                return ResourceManager.GetString("CompanyStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string CompanyStreetNumber {
            get {
                return ResourceManager.GetString("CompanyStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTW.
        /// </summary>
        internal static string CompanyVAT {
            get {
                return ResourceManager.GetString("CompanyVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE0542.455.672.
        /// </summary>
        internal static string CompanyVATNumber {
            get {
                return ResourceManager.GetString("CompanyVATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacteer ons.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@coiffureshop.com.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haarverlengingen.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/davinascoiffureshop/.
        /// </summary>
        internal static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vrijdag.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/davinascoiffureshop/.
        /// </summary>
        internal static string InstagramLink {
            get {
                return ResourceManager.GetString("InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een afspraak.
        /// </summary>
        internal static string MakeAnAppointment {
            get {
                return ResourceManager.GetString("MakeAnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maandag.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingsuren.
        /// </summary>
        internal static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00 - 20:00.
        /// </summary>
        internal static string OpeningHoursFriday {
            get {
                return ResourceManager.GetString("OpeningHoursFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 - 17:00.
        /// </summary>
        internal static string OpeningHoursMonday {
            get {
                return ResourceManager.GetString("OpeningHoursMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00 - 17:00.
        /// </summary>
        internal static string OpeningHoursSaturday {
            get {
                return ResourceManager.GetString("OpeningHoursSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00 - 11:00.
        /// </summary>
        internal static string OpeningHoursSunday {
            get {
                return ResourceManager.GetString("OpeningHoursSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00 - 21:00.
        /// </summary>
        internal static string OpeningHoursThursday {
            get {
                return ResourceManager.GetString("OpeningHoursThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00 - 16:00.
        /// </summary>
        internal static string OpeningHoursTuesday {
            get {
                return ResourceManager.GetString("OpeningHoursTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00 - 18:30.
        /// </summary>
        internal static string OpeningHoursWednesday {
            get {
                return ResourceManager.GetString("OpeningHoursWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl.
        /// </summary>
        internal static string OptiosBookingCulture {
            get {
                return ResourceManager.GetString("OptiosBookingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 059 730 185.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3259730185.
        /// </summary>
        internal static string PhoneNumberInternational {
            get {
                return ResourceManager.GetString("PhoneNumberInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davina&apos;s Coiffure Shop.
        /// </summary>
        internal static string SalonName {
            get {
                return ResourceManager.GetString("SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaterdag.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijslijst diensten.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davina&apos;s Coiffure Shop.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zondag.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donderdag.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dinsdag.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/DsCoiffureShop.
        /// </summary>
        internal static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woensdag.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
